ARG flavor=8-jdk-hotspot

FROM adoptopenjdk:$flavor as base

LABEL maintainer="wayfarermusic0130@gmail.com"

#==========================================================================
# Base
#==========================================================================
